import Head from "next/head";
import styles from "@/styles/Home.module.css";
import dynamic from "next/dynamic";
import { injectScript } from "@module-federation/nextjs-mf/utilities";

const isServer = typeof document == undefined;

const remote = injectScript({
  global: "componentsRemote",
  url: `http://localhost:3003/_next/static/${
    isServer ? "ssr" : "chunks"
  }/remoteEntry.js`,
});
const remoteComponent = remote.then((container) =>
  container.get("./MyComponent").then((componentFactory) => componentFactory())
);
const MyComponent = dynamic(() => remoteComponent);

// Error: Hydration failed because the initial UI does not match what was rendered on the server.
// const MyComponent = dynamic(() => import("componentsremote/MyComponent"), {
//   ssr: true,
// });

// Error: Hydration failed because the initial UI does not match what was rendered on the server.
// const MyComponent = require("componentsremote/MyComponent").default;

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Loading a remote component:</h1>
        <MyComponent />
      </main>
    </>
  );
}
