import Head from "next/head";
import styles from "@/styles/Home.module.css";
import dynamic from "next/dynamic";
import { loadRemote } from "@module-federation/runtime";

const MyComponent = dynamic(() => loadRemote("componentsremote/MyComponent"));

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Loading a remote component:</h1>
        <MyComponent />
      </main>
    </>
  );
}
